# Generated by Django 3.2.9 on 2021-12-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='customer_type',
            field=models.CharField(max_length=20),
        ),
    ]
