# Generated by Django 3.2.9 on 2021-12-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20211211_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
