# Generated by Django 3.2.9 on 2021-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_payments_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='usd_amount',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='btc_amount',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='btc_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='usd_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
