# Generated by Django 3.2.9 on 2021-12-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20211211_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sell_flag',
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_per',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(default='buy', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='btc_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_txn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
