# Generated by Django 3.2.9 on 2021-12-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20211211_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
